### ISSUE TITLE
CORS - ERR:BLOCKED_BY_CLIENT [discussion]

### ISSUE THREAD

**Issue by frdomovic** [calimero-network/admin-dashboard#26]
## CORS - ERR:BLOCKED_BY_CLIENT [discussion]
The admin dashboard page on first start opens up the "setup" page, where user should put the node url which is going to be saved in local storage and used for all the api calls later. The image 1 presents the setup component and clicking on "Set node URL" does an api request on endpoint `/health` on the given url.  

![Screenshot 2024-06-27 at 13 35 35](https://github.com/calimero-network/admin-dashboard/assets/93442516/81ade4cc-c320-4131-acf6-59fcf723598b)

There are currently 3 flows possible on this screen:
1.  The node is running and the endpoint returns` 200 - { data: { status: true } }`
2. The node url is not valid and it returns connection failed -` Failed to load resource: Could not connect to the server`
3. The node url returns `ERR:BLOCKED_BY_CLIENT `

<img width="661" alt="Screenshot 2024-06-27 at 13 20 26" src="https://github.com/calimero-network/admin-dashboard/assets/93442516/a127fdd4-bb16-4e8a-bdcf-6a177c04dfa3">

![Screenshot 2024-06-27 at 13 21 04](https://github.com/calimero-network/admin-dashboard/assets/93442516/b0e25907-90af-4716-88c9-e7fca4223c6c)

The flow on number 3 is an bug that should be fixed. 
It occurs on Safari, Firefox, Brave, and sometimes on google chrome (although I personally did not have this issue)

On first this seems like it is a CORS issue but adding origin headers on both frontend application and/or server the issue is still there.

Searching for similar issues I found these: 
1. [issue 1](https://stackoverflow.com/questions/39076180/https-page-was-not-allowed-to-run-insecure-content-from-safari-extension-uri)
2. [issue 2](https://github.com/ipfs/js-ipfs/issues/3154)
3. [issue 3](https://forum.unity.com/threads/cors-blocking-on-github-pages-even-with-headers-set.1581033/)

They mentioned fixing the issue in [this](https://x.com/invisiblecomma/status/575219895308324864) tweet but this was 2015 and was removed later.

The conclusions of checking the similar issue:
```
This is not to do with CORs, this is because we're trying to access content in an insecure way from a secure location - the page is loaded over https but the API request is made over http.
You used to be able to turn this off as a Safari preference but it's been removed, which is probably for the best.
```
Additionally I created a new nodeJS server and tried to connect to it from github pages (again https > http) it was failing, but when I deployed the same nodeJS server with no additional cors updates to Digital Ocean (https > https) it started working.

[DISCUSSION]
How do we proceed, deploy admin dashboard application on Vercel and check if it works there?
cc: @MatejVukosav @xilosada

**Comment by MatejVukosav** [comment]
What is the difference of admin dashboard being on GitHub pages or on Vercel?

**Comment by frdomovic** [comment]
I haven't seen [this](https://forum.unity.com/threads/cors-blocking-on-github-pages-even-with-headers-set.1581033/) issue on Vercel and I did test similar things before with Vercel so might worth a try.
Any other solution to recomment?

**Comment by frdomovic** [comment]
Hosted on vercel + netlify it has the same issue. It works on Chrome but brave and safari get Cors blocked again.
[webpage](https://admin-dashboard-fork.vercel.app/admin-dashboard/) - @MatejVukosav @xilosada 
<img width="1457" alt="Screenshot 2024-07-02 at 17 14 46" src="https://github.com/calimero-network/admin-dashboard/assets/93442516/b18a2082-dfad-4703-9dad-6de317dc4cc1">
<img width="1173" alt="Screenshot 2024-07-02 at 17 17 03" src="https://github.com/calimero-network/admin-dashboard/assets/93442516/49b44fd0-52d0-4262-8ef5-282ebfeda56b">

**Comment by frdomovic** [comment]
Leaving this open for future, but for now we will use both node server and admin dashboard locally without Github pages.
